### ISSUE TITLE
fix - Removing duplicated methods of role and authorities validation 

### ISSUE THREAD

**Issue by bellaabdelouahab** [ISIL-ESTE/Student-Workflow-Organizer#70]

**Comment by bellaabdelouahab** [comment]
@muttaqin1 so remind me again how we can validate the role, 
in the role model we have authorities and restrictions but in restrictedTo method that you have written 
```js
const restrictTo =
  (...actions) =>
  (req, res, next) => {
    if (hasAuthority(req.user, actions)) {
      if (!isRestricted(req.user, actions)) next();
      else
        next(
          new AppError(
            403,
            'fail',
            'You are restricted from performing this action, contact the admin for more information'
          )
        );
    } else
      next(new AppError(
          403,
          'fail',
          'You do not have permission to perform this action'
        )
      );
  };
```
you validate the actions regardless of what is their nature ( authorities || restrictions ) 

so we may need a function to map the roles to actions ,

**Comment by muttaqin1** [comment]
if the required Action exists is in the authorities array of the user obj that means the user has the permission to perform the action thats why i am checking this condition.

```js 
if (hasAuthority(req.user, actions)) {
```
If the user has the required action not only in the authorities array but also the restrictions array. Because of the existence of the Action in the restrictions array the user can't perform the Action.

```js
if (!isRestricted(req.user, actions)) next();
```

To validate the role and authorities together or separately validate role and authorities we can do this:

```js
const restrictTo = (...roles) => {
    if (roles) validateRole(); // if validation fails the user cant jump to next step.
    // jump to next step
    return (...actions) => {
        // if actions are passed in then validate them or else just jump to next step
        if (actions)
            return (req, res, next) => {
                if (hasAuthority(req.user, actions)) {
                    if (!isRestricted(req.user, actions)) next();
                    else
                        next(
                            new AppError(
                                403,
                                'fail',
                                'You are restricted from performing this action, contact the admin for more information'
                            )
                        );
                } else
                    next(
                        new AppError(
                            403,
                            'fail',
                            'You do not have permission to perform this action'
                        )
                    );
            };
        // the next step
        return (req, res, next) => next();
    };
};
```
this is just a psudo code. I believe it will be helpful.
@bellaabdelouahab

**Comment by muttaqin1** [comment]
**so we may need a function to map the roles to actions**

Are you talking about mapping db role records to this:
```js
type:"ADMIN",
authorities:[],
restrictions:[]
}
```
I didn't understand. Can you please elaborate more about this?

**Comment by bellaabdelouahab** [comment]
I want to explain something from the first place we added role base authorization in order to not go throw all authorities and restrictions of a role so for example if we have /admin/* as collection of endpoint we just say restrictedto("admin") without going throw all the authorities and restrictions of the admin
And then inside of this collection in one of endpoints for example we can say if(isRestrictedFrom("UPDATE-CALLANDER") return apperror

@muttaqin1

**Comment by muttaqin1** [comment]
> I want to explain something from the first place we added role base authorization in order to not go throw all authorities and restrictions of a role so for example if we have /admin/* as collection of endpoint we just say restrictedto("admin") without going throw all the authorities and restrictions of the admin
> And then inside of this collection in one of endpoints for example we can say if(isRestrictedFrom("UPDATE-CALLANDER") return apperror
> 
> @muttaqin1 

Great idea. This is a very efficient solution. You can go ahead and implement your idea.

@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
Is it good or you re just saying that? @muttaqin1 hhh

**Comment by muttaqin1** [comment]
Its definitely good. Because of you i have came up with a great solution to this.
For long time we are facing problem for 
this:
```js
router.use(restrictTo("ADMIN","SUPER_ADMIN"))
```
because of this line in the beginning of our routes. Our custom roles can't pass below or access the route. But now we can do this:

**There will be only 3 roles:**
- [ ] ADMIN
- [ ] SUPER_ADMIN
- [ ]  USER

Now we will create custom roles right?

We will create custom roles such as _MODERATOR_ and only use their authorities and restrictions.
We will not add the  name of  this role in the **roles** array of the user object.

As we know the role _MODERATOR_ will have some authorities and restrictions we will push the to our user object**authorities** and **restrictions** array.

This is how a **ADMIN** role or **SUPER_ADMIN** role will inharit custom roles.

We have to add a property **InharitedCustomRoles** in the user object so that when we have to remove the authorities and restrictions of the custom role from  the user object. We can check if the user has really inharited that role.If true we will remove those authorities and restrictions.

```js
const user = {
authorities:[],
restrictions [],
roles:["USER", "ADMIN"],
inheritedCustomRoles:["MODERATOR"]

}
```
what do you think about this?
@bellaabdelouahab

**Comment by muttaqin1** [comment]
I will tell more about this but first i want to hear your thoughts

**Comment by bellaabdelouahab** [comment]
`
We have to add a property InheritedCustomRoles in the user object so that when we have to remove the authorities and restrictions of the custom role from the user object. We can check if the user has really inherited that role.If true we will remove those authorities and restrictions.
`
i didn't understand this, what will happen if we don't add InheritedCustomRoles

**Comment by muttaqin1** [comment]
InheritedCustomColes will keep all the records of how many custom roles is being inherited by the user.
- [ ] when we will demote a user we can check if the user really has the role.
- [ ] we can filter how many users are using 
that custom role

@bellaabdelouahab

**Comment by bellaabdelouahab** [comment]
But why bot just keep it in roles field?
@muttaqin1
And btw give me your WhatsApp number so I can reach out more quickly

**Comment by muttaqin1** [comment]
If we keep custom roles in roles field:
```js
const user = {
roles:[admin, user, costumerole... ]
} 
```
this code only lets admin and user to access the route. So custom roles won't work.
```js
// This is not dynamic.
router.use(restrictTo("ADMIN","SUPER_ADMIN"))
```

Thats why i have came up with this idea.
But i have thought a lot about this and this idea also have some flaws. So forgot about this.

So we can remove only the custom roles feature and Implement your idea. It will be best.
@bellaabdelouahab

**Comment by muttaqin1** [comment]
whatsApp: +8801746371794

@bellaabdelouahab
